name: Daily Netlify Build

on:
  schedule:
    - cron: "0 6 * * *" # every day at 6 AM UTC
  workflow_dispatch: # optional - to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/6904798b8ff04c6f0173594f
